// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgrSAz3xp93QlQzuVbGYk1xyR9oZ0Uvc',
    appId: '1:1071459524631:web:4617d3662293f71e9ffc52',
    messagingSenderId: '1071459524631',
    projectId: 'messageme-app-f0da1',
    authDomain: 'messageme-app-f0da1.firebaseapp.com',
    storageBucket: 'messageme-app-f0da1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPqFn3-rtuKrgG7SjhZJ42PAe9Rg6Bm8',
    appId: '1:1071459524631:android:90a37ba93a558fc39ffc52',
    messagingSenderId: '1071459524631',
    projectId: 'messageme-app-f0da1',
    storageBucket: 'messageme-app-f0da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVry76a5lWMRpLyL69bNKc4jWoGItnKPs',
    appId: '1:1071459524631:ios:2cbc435cbddbf7e59ffc52',
    messagingSenderId: '1071459524631',
    projectId: 'messageme-app-f0da1',
    storageBucket: 'messageme-app-f0da1.firebasestorage.app',
    androidClientId: '1071459524631-o38piqjp37mf0ls862o031kbe3jvb5um.apps.googleusercontent.com',
    iosClientId: '1071459524631-gjuf86ai83m7d9ta1qecmsio8d9nu5ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkgrSAz3xp93QlQzuVbGYk1xyR9oZ0Uvc',
    appId: '1:1071459524631:web:4617d3662293f71e9ffc52',
    messagingSenderId: '1071459524631',
    projectId: 'messageme-app-f0da1',
    authDomain: 'messageme-app-f0da1.firebaseapp.com',
    storageBucket: 'messageme-app-f0da1.firebasestorage.app',
  );
}
